### ISSUE TITLE
do you have any sample apps that execute permission escalation attack?

### ISSUE THREAD

**Issue by Tigerly** [Phylu/ba#1]
Hello,

I'm a researcher doing malware detection. I was wondering whether you have some sample apps that execute permission escalation attack? Thanks in advance!

**Comment by Phylu** [comment]
Hi Tigerly,

you wan find it here: https://github.com/Phylu/ba/tree/master/exynos_root/ExynosRoot
This attack worked on an unpatched Samsung N8000 as described in my research paper: https://www.os.in.tum.de/fileadmin/w00bdp/www/Lehre/Abschlussarbeiten/bathesis_jmaier_final.pdf

**Comment by Tigerly** [comment]
Thanks! It's helpful! :-)
